# This docker-compose.yml file is used only for local dev env. Please don't use it anywhere else.

version: "3.9"

services:
  db:
    container_name: test-db
    image: postgres:13.0-alpine
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD-SHELL", "test -d test -U test"]
      interval: 5s
      retries: 5
    restart: always

  backend:
    container_name: test-backend
    build:
      context: ./backend
      dockerfile: ./Local.Dockerfile
    command:
      [
        "./local_entrypoint.sh",
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8800",
      ]
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    ports:
      - "8800:8800"

  redis:
    container_name: test-redis
    image: redis:alpine

  celery-worker:
    container_name: test-celery-worker
    build:
      context: ./backend
      dockerfile: ./Local.Dockerfile
    command: celery -A core worker -E --loglevel info
    volumes:
      - ./backend:/app/backend

  celery-beat:
    container_name: test-celery-beat
    build:
      context: ./backend
      dockerfile: ./Local.Dockerfile
    command: celery -A core beat --loglevel info
    volumes:
      - ./backend:/app/backend

  flower:
    container_name: test-flower
    build:
      context: ./backend
      dockerfile: ./Local.Dockerfile
    command: celery -A core flower --port=5566 --loglevel info
    ports:
      - "5566:5566"
    volumes:
      - ./backend:/app/backend
volumes:
  postgres_data:
